name: domino
description: An incremental DOM library, with support for virtual DOM and components.
version: 0.8.0
homepage: https://github.com/agilord/domino/tree/main/domino

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  lints: ^1.0.0
  puppeteer: ^2.5.0
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  test: ^1.3.0
